version: "3"

services:
   smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'

   django2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./student_management/student_management/.env
    ports:
      - "9000:9000"
    volumes:
      - static_volume:/app2/static
    
   nginx:
    image: bitnami/nginx
    volumes:
      - ./nginx2.http.config:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app2/static
    ports:
      - "8080:8080"
    depends_on:
      - django2
    restart:
      on-failure:5

volumes:
  static_volume:
