version: "3"

services:
   smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'

   django2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./student_management/student_management/.env
    ports:
      - "9000:9000"
    volumes:
      - static_volume:/app2/static

volumes:
  static_volume:
